### ISSUE TITLE
Missing Parameter in REDCap_API_Importer_CSV.sas 

### ISSUE THREAD

**Issue by zhangm3** [RMPDC-BDM/SAS2REDCap#2]
Thank you so much for sharing the code. It is very helpful. 
 In REDCap_API_Importer_CSV.sas line 216 %calc_CSV(fsize_kB=&filesize.); is missing data= parameter. It should be %calc_CSV(fsize_kB=&filesize.,data=&data.);
Hope it makes sense.
Thanks again.

**Comment by Randy9** [comment]
Thank you Jim! I did know there was a slight issue with that macro, and of course it was a simple fix. Thanks for pointing it out. I hope your usage of this code works well for you moving forward.

**Comment by zhangm3** [comment]
Thanks a lot. It is awesome.
Jim
