### ISSUE TITLE
Read Access Violation with PROC HTTP

### ISSUE THREAD

**Issue by jmkurka83** [RMPDC-BDM/SAS2REDCap#3]
Hello,
I'm trying to use SAS to call the REDCap API and am having issues. I've found numerous code examples, all of which have similarities, using PROC HTTP. Here is the code I'm focusing on:
`data _null_ ;
file my_in ;
put "%NRStr(content=record&type=flat&format=csv&mytoken=)&mytoken%NRStr(&)";
run;
proc http
in=my_in
out= my_out
headerout = status
url ="https://redcap.url.edu/api"
method="post";
run;`
Here is my error:
`The SAS task name is [HTTP (2)]
ERROR:  Read Access Violation HTTP (2)
Exception occurred at (02457E08)
Task Traceback
Address   Frame     (DBGHELP API Version 4.0 rev 5)
0000000002457E08  000000000B91E730  tkmk:tkBoot+0x460C8
0000000002457F41  000000000B91E7B0  tkmk:tkBoot+0x46201
00000000024597A6  000000000B91E800  tkmk:tkBoot+0x47A66
000000000244442B  000000000B91E870  tkmk:tkBoot+0x326EB
000000000331FA3E  000000000B91E878  sashost:Main+0xA7F1E
0000000008E4E6F8  000000000B91E8F8  tkhttp:tkextver+0x318
3                                                          The SAS System                             13:00 Monday, October 28, 2019

0000000008DCD741  000000000B91F290  tkhttp:tkhttp+0xC741
0000000008DC6CEC  000000000B91F390  tkhttp:tkhttp+0x5CEC
0000000008AB5020  000000000B91F398  sashttp:tkvercn1+0x3FE0
0000000008AB1B20  000000000B91F9E0  sashttp:tkvercn1+0xAE0
000000000483C477  000000000B91F9E8  sasxshel:tkvercn1+0x4B437
0000000008AB8622  000000000B91FB00  sashttp:tkvercn1+0x75E2
0000000008AB115A  000000000B91FBF0  sashttp:tkvercn1+0x11A
0000000003288A2B  000000000B91FF20  sashost:Main+0x10F0B
000000000328E66D  000000000B91FF50  sashost:Main+0x16B4D
00007FFED8BC3DC4  000000000B91FF58  KERNEL32:BaseThreadInitThunk+0x14
00007FFED9273691  000000000B91FF88  ntdll:RtlUserThreadStart+0x21`

Any ideas on what's causing this?

**Comment by Randy9** [comment]
Hi Jonathan,

I'm sorry to hear you're having troubles with the API macro. Based on the log information you've provided, this issue does not seem to be on the SAS side. This to me seems to be some sort of access permissions issue on your REDCap server administrator side. Do you have someone who hosts your REDCap server you could reach out to? That would be my first suggestion for you.

I hope this helps.

Kind regards,
Randy

**Comment by jmkurka83** [comment]
Hi Randy,
Thank you for looking into this. Yes, I've been exploring that avenue as well. I discussed it with my coworker who is in charge of the back-end side of REDCap (we're the only 2 admins), and looking at the TLS client levels. The REDCap server is currently enforcing TLS 1.2. We're looking for support from SAS on why it's not connecting though. If you have any knowledge of this, any suggestions are appreciated. Thanks again!
